Fix for: - zrok - ziti-router
Remove from spec.template.metadata.labels duplicated already defined labels:
- app.kubernetes.io/managed-by
- app.kubernetes.io/instance
- helm.sh/chart

So it would not prevent deploying these helm charts, otherwise you can see error "unmarshal errors [...] mapping key [...] already defined"

```shell
kustomize build ./kustomizations --enable-helm > ./openziti.kustimized.yaml
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 27: mapping key "app.kubernetes.io/managed-by" already defined at line 22
  line 29: mapping key "app.kubernetes.io/instance" already defined at line 23
  line 25: mapping key "helm.sh/chart" already defined at line 24
```